### ISSUE TITLE
Previews on the Song Wheel do not respect #SAMPLELENGTH values

### ISSUE THREAD

**Issue by Xytonic** [TaroNuke/Simply-Love-NotITG-ver.-#12]
Another minor issue that may not be NotITG related: Previews on the Song Wheel: Sometimes (but not always) it seems like the preview music _fades out_  rather than _looping_ at the end of the song preview duration.  The behavior seems to be consistent per-song -- a song that loops on the beat will do so every time and vice versa -- but I haven't found a rhyme or reason to  it.

It seems like the bug-of-a-bug, but in case it helps: If you go in and set a preview for a song in the editor and exit with out saving, the new value will be used until you close the client.

Example:
The loop in a freshly-launched client:
https://user-images.githubusercontent.com/77179964/120878705-27472780-c58c-11eb-81cd-506f77ee1424.mp4

The loop with the same start and end times after redefining the sample length in the editor:
https://user-images.githubusercontent.com/77179964/120878708-2adaae80-c58c-11eb-9cf6-c929fa960e28.mp4

The probably-bug-of-a-bug:
https://user-images.githubusercontent.com/77179964/120878806-d08e1d80-c58c-11eb-9a44-0f687d2202e1.mp4

**Comment by gwellman** [comment]
Song preview behavior has been a bit spotty with regards to aligning loop timings since back to at least 3.95, so I don't think it's NotITG related. I'll describe the issues I've had, let me know if this sounds like what you're experiencing: In my experience, if the song preview is too long relative to an integer number of beats... how long is "too long" I haven't experimented with in a while, seems kind of iffy... then it ends up "rounding up" to the next beat, so e.g. if the song preview is exactly 32 beats long and Stepmania is in a bad mood then it fades out at the end of 32 beats, but also decides that those 32 beats won't fit in 32 beats of preview time and loops once every 33 beats instead. For this reason, I usually make the previews 1/64th or so shorter than I want to avoid this behavior, but if there are tempo changes around the start or end of the preview music, this behavior gets more complicated and it's harder to account for it. Does that sound like the behavior you're experiencing?
For the not respecting preview timing thing, at least. That thing with sample music getting cached wrong or something after editing is definitely odd and something I haven't seen before.

**Comment by Xytonic** [comment]
I did a little digging based on that, and yes, it looks like this is a 3.95 bug: Tried that song in OpenITG (1.0.3.0) and had the same problem, but in StepMania 5 it loop as expected.  When I tried ending the preview sooner (one 64th note / 0.019 seconds in this case) and it loops.  I'll close this issue since it's not a theme bug.  Thank you for the workaround!
